# 02 - Cleaning & Data Fixes
Document each fix and rationale.

In [2]:
import os, sys
sys.path.append(os.path.abspath(".."))  

import pandas as pd
from src.preprocessing import basic_impute, summarize_missing

# Load the raw dataset
df = pd.read_csv("../data/raw/heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,2,120,236,0,0,178,0,0.8,2,0,2,1
4,57,0,2,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
df_imputed = basic_impute(df.copy(), numeric_strategy='median')
display(summarize_missing(df_imputed))

          missing  pct_missing
age             0          0.0
sex             0          0.0
cp              0          0.0
trestbps        0          0.0
chol            0          0.0
fbs             0          0.0
restecg         0          0.0
thalach         0          0.0
exang           0          0.0
oldpeak         0          0.0
slope           0          0.0
ca              0          0.0
thal            0          0.0
target          0          0.0

In [4]:
cat_cols = df_imputed.select_dtypes(include=['object','category']).columns.tolist()
df_encoded = pd.get_dummies(df_imputed, columns=cat_cols, drop_first=True)

df_encoded.to_csv("../data/processed/heart_processed.csv", index=False)
print("Saved processed dataset to data/processed/heart_processed.csv")
df_encoded.shape

Saved processed dataset to data/processed/heart_processed.csv

(30, 14)

#Cleaning Results
- Applied median imputation (no missing values to fix in this dataset)
- Checked for categorical variables (none found here) 
- Saved cleaned dataset as `data/processed/heart_processed.csv`.